# Generated by Django 4.1.3 on 2022-11-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Postulante',
        ),
    ]
